---
- name: Playbook for creating Jenkins image and starting
  hosts: build_server 
  remote_user: cddeploy
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - jenkins/vars/root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: jenkins 
