---
- name: Create Volume for registry
  docker_volume:
    name: registry_volume
        
- name: Install docker registry
  tags: run_registry
  community.docker.docker_container:
    name: docker_registry
    image: registry:{{ img_version }}
    volumes:
      - registry_volume:{{ volume_path }}
    restart: true
    ports:
      - "{{ ports[0] }}:{{ ports[1] }}"
