---
- name: Create Volume for registry
  docker_volume:
    name: registry_volume
        
- name: Install docker registry
  tags: run_registry
  community.docker.docker_container:
    name: docker_registry
    image: registry:latest
    volumes:
      - registry_volume:/var/lib/registry
    restart: true
    ports:
      - "5000:5000"
