---
- name: Install dependencies
  yum:
    name:
      - java
    use_backend: "yum"
    state: latest
  vars:
    ansible_python_interpreter: /usr/bin/python
        
- name: Volume creation
  docker_volume:
    name: sonarqube_data
  docker_volume:
    name: sonarqube_logs
  docker_volume:
    name: sonarqube_extensions
    
- name: Clone Git repository
  tags: config_update 
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ target_directory }}"
    key_file: "{{ sshkey }}"
    clone: yes
    update: yes
    version: "feature/sonar"
    accept_hostkey: yes
    force: yes
  become_user: cddeploy

- name: Run sonar
  tags: run_sonar
  community.docker.docker_container:
    name: sonarqube
    image: sonarqube:latest
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - /home/cddeploy/sonarqube/conf:/opt/sonarqube/conf
      - /home/cddeploy/sonarqube/jdbc:/opt/sonarqube/extensions/jdbc-driver/mssql

    env:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    restart: true
    ports:
      - "9000:9000"